[package]
name = "dancing-links"
version = "0.1.1"
description = "Exact cover solver using dancing links technique"
authors = ["Declan Kelly <dkelly.home@gmail.com>"]
repository = "https://github.com/declanvk/dancing-links/"
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["algorithms", "data-structures", "sudoku", "latin-square", "dancing-links"]
categories = ["algorithms", "data-structures", "mathematics"]

exclude = [
    ".github/",
]

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
bumpalo = "3.4"
